package esmj3dfo76.data.records;

import java.util.ArrayList;
import java.util.List;

import esfilemanager.common.data.record.Record;
import esfilemanager.common.data.record.Subrecord;
import esmj3d.data.shared.records.RECO;

import esmj3dfo76.data.subrecords.LVLD;
import esmj3dfo76.data.subrecords.LVLF;
import esmj3dfo76.data.subrecords.LVLO;
/**
 * https://falloutck.uesp.net/wiki/LeveledItem
 * A Leveled Item is a list that will generate one or more items based on the current level of the player. 
 * Leveled Item objects cannot be placed in the world directly. 
 * To use them, add them to a Container, or use the LeveledItem tab on an item reference to replace the reference with the item generated by the leveled list.
 * Dummy objects are most often used for this purpose. 
 */
public class LVLI extends RECO
{
	

	public LVLD LVLD = null;

	public LVLF LVLF = null;

	public LVLO[] LVLOs = null;

	public LVLI(Record recordData)
	{
		super(recordData);

		ArrayList<LVLO> LVLOsl = new ArrayList<LVLO>();

		List<Subrecord> subrecords = recordData.getSubrecords();
		for (int i = 0; i < subrecords.size(); i++)
		{
			Subrecord sr = subrecords.get(i);
			byte[] bs = sr.getSubrecordData();

			if (sr.getSubrecordType().equals("EDID"))
			{
				setEDID(bs);
			}
			else if (sr.getSubrecordType().equals("OBND"))
			{

			}
			else if (sr.getSubrecordType().equals("LLCT"))
			{

			}
			else if (sr.getSubrecordType().equals("LVLG"))
			{

			}
			else if (sr.getSubrecordType().equals("LVLD"))
			{
				LVLD = new LVLD(bs);
			}
			else if (sr.getSubrecordType().equals("LVLF"))
			{
				LVLF = new LVLF(bs);
			}
			else if (sr.getSubrecordType().equals("LVLO"))
			{
				LVLOsl.add(new LVLO(bs));
			}
			else if (sr.getSubrecordType().equals("DATA"))
			{

			}
			else if (sr.getSubrecordType().equals("LVLM"))
			{

			}
			else if (sr.getSubrecordType().equals("LLKC"))
			{

			}
			else if (sr.getSubrecordType().equals("LVSG"))
			{

			}
			else
			{
				System.out.println("unhandled : " + sr.getSubrecordType() + " in record " + recordData + " in " + this);
			}

			// transfer to arrays
			LVLOs = new LVLO[LVLOsl.size()];
			LVLOsl.toArray(LVLOs);
		}
	}

}
